spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Controller of Sonic Cloud Real Machine Platform"
  profiles:
    active: @project.artifactId@,jdbc,logging,user
  main:
    allow-circular-references: true